/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.jasonhk.hkiit.itp3914.assignment;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GomokoTest {
    @Test void appHasAGreeting() {
        Gomoko classUnderTest = new Gomoko();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
