#!/bin/bash
set -euo pipefail

sleep 6

input "-1 0" 2
input "0 10" 4

input "0 1" 2
input "0 1" 4

input "0 2" 2
input "1 1" 2
input "1 2" 2
input "2 3" 2
input "2 2" 2
input "3 1" 2
input "2 1" 2
input "3 2" 2
input "3 0" 2
input "3 3" 2
input "0 3"
